#!/bin/bash

print_usage () {
	printf "Usage: $0 [options] rows cols\n\trows and cols >= 1\n\t-w (true || false)\twrap around\n\t-h\t\tdisplay help\n"
	exit 0
}

# Parse options
while getopts :hw: opt; do
	case $opt in
		w)
			w=${OPTARG}
			(( w == true || w == false )) || print_usage
			dconf write /org/compiz/profiles/unity/plugins/wall/allow-wraparound $w
		;;
		*)
			print_usage
		;;
	esac
done

# Parse hsize and vsize
if [[ $(($# - $OPTIND)) -lt 1 ]]; then
	if [[ $w ]]; then 
		exit 0
	else
		print_usage
	fi
fi

rows=${@:OPTIND:1}
cols=${@:OPTIND+1:1}

# Check type
re=^[0-9]+$
if ! [[ $rows =~ $re && $cols =~ $re ]] ; then
	print_usage
fi

# Ensure greater than 1
if [[ $rows == 0 || $cols == 0 ]] ; then
	print_usage
fi

# Set screen size
dconf write /org/compiz/profiles/unity/plugins/core/hsize $cols
dconf write /org/compiz/profiles/unity/plugins/core/vsize $rows
